### ISSUE TITLE
SSL issue when downloading libreswan

### ISSUE THREAD

**Issue by mertdumenci** [jlund/streisand#355]
Hey,

I'm trying to set up streisand on Digital Ocean, and it's giving me an SSL validation error when downloading libreswan. I tried 3 different data centers for the Droplet, and libreswan's downloads seem to be fine (I can fetch them locally just fine.)

Here's the exact error:

```
TASK [l2tp-ipsec : Retrieve the Libreswan source code] *************************
fatal: [{omitted}]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for download.libreswan.org:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

Thank you!

**Comment by TonyZTan** [comment]
I am experiencing the same issue here. According to [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=download.libreswan.org&s=193.110.157.101), the server certificates are fine, but the server does require SNI support.

**Comment by TonyZTan** [comment]
I submitted a patch (#356) that should fix this issue.

**Comment by denoza** [comment]
Thanks for the fix @TonyZTan. It worked for me!

**Comment by mertdumenci** [comment]
This fixed my issue as well. Thank you, @TonyZTan.

**Comment by jlund** [comment]
And now it's merged! I'm kind of surprised this hasn't come up before. SNI is quite common. Thanks again, @tonyztan!

**Comment by nabilfreeman** [comment]
Hi guys, I'm unfortunately still receiving this exact error on the up-to-date version of `master` as of 2016-09-27.

I looked through the commit history since PR #356 and noticed that the `pip` fix has been moved around the repo a few times and that the download location of Libreswan has changed from a Cloudfront server to the official website. Is anybody else experiencing this error, and could anybody please advise a fix?

In the meantime, I rolled back to @tonyztan's commit and got a server successfully set up, but I'm 70 commits behind master & worried I'm missing important security fixes.

**Comment by jlund** [comment]
On what provider and Linux distribution are you seeing this issue? The version of Python in Ubuntu 14.04 natively supports SNI (which was the original cause of this problem). In theory at least, this workaround should no longer be necessary.

**Comment by jlund** [comment]
Err, I meant to say The version of Python in Ubuntu **_16.04_** natively supports SNI. Editing the comment above to reflect reality :)

**Comment by cpu** [comment]
This is being worked around with https://github.com/jlund/streisand/pull/633 

Libreswan's download servers [fail requests without SNI, sometimes](https://lists.libreswan.org/pipermail/swan/2017/002125.html), and they are both aware of it & not willing to fix it.

I'm going to close this issue since there's no action to take at this time. Thanks all!
